version: "3.8"
services:
  app:
    container_name: app-cheese-cake
    build:
      args:
        user: cheese-cake
        uid: 1000
      context: ./docker/laravel
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/code
    volumes:
      - .:/var/www/code
      - ./docker/laravel/php.ini:/usr/local/etc/php/php.ini-development
    networks:
      - cheese-cake-network

  web:
    container_name: web-cheese-cake
    image: nginx:alpine
    restart: unless-stopped
    ports:
        - 8888:80
    volumes:
        - .:/var/www/code
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cheese-cake-network

  database:
    container_name: mysql-cheese-cake
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - cheese-cake-database:/var/lib/mysql
      - ./docker/mysql/database:/docker-entrypoint-initdb.d
    ports:
      - 33062:3306
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - cheese-cake-network

networks:
  cheese-cake-network:
    driver: bridge

volumes:
  cheese-cake-database:
    driver: local
